FreedomBen/malan

lib/malan/accounts.ex
lib/malan/accounts/session.ex
lib/malan/accounts/user.ex
lib/malan/utils.ex
lib/malan_web/controllers/user_controller.ex
lib/malan_web/router.ex
lib/malan_web/views/user_view.ex
priv/repo/migrations/20210802210324_add_password_reset_token_column.exs
test/malan/accounts_test.exs
test/malan/utils_test.exs
test/malan_web/controllers/user_controller_test.exs

New endpoints:
POST /users/:id/reset_password        --- Returns {"password_reset_token": "abc"}
PUT  /users/:id/reset_password/:token --- { "new_password": "<whatever>" }
Currently because the password reset token is returned in-band, only an
authenticated administrator user is allowed to call these endpoints.
Fixes #18

Add endpoints for password reset functionality

---

lib/malan/accounts/user.ex
test/malan/user_schema_test.exs
test/malan_web/controllers/user_controller_test.exs

You must still be an admin to set them, but there aren't restrictions
on which roles exist

Allow arbitary roles to be set

---

lib/malan/accounts.ex
lib/malan_web/controllers/auth_controller.ex
lib/malan_web/controllers/user_controller.ex
test/malan/accounts_test.exs
test/malan_web/controllers/user_controller_test.exs

The client doesn't always have the user's ID but does have the username.
For situations like this it's really useful to be able to look up the
user by username instead of ID.
Fixes #29

Allow using username or ID for user endpoints

---

lib/malan_web.ex

The really useful log messages that are buil in to phoenix are :debug
messages.  This changes them to be :info messages instead so they show
up in the logs without having to change the production log level.
See:  https://www.verypossible.com/insights/thoughtful-logging-in-elixir-a-phoenix-story
Fixes: #43

Increase production logging level

---

lib/malan/accounts.ex
lib/malan/accounts/transaction.ex
lib/malan_web/controllers/session_controller.ex
lib/malan_web/controllers/user_controller.ex
priv/repo/migrations/20220220023537_add_success_to_transactions.exs
test/malan/accounts_test.exs
test/malan/transaction_schema_test.exs
test/support/fixtures/accounts_fixtures.ex

This way we can see whether the transaction was successful or not, and
we can query based on that.  Previously you could infer success from the
"what" contents, but it wasn't explicit.  This is explicit and
queryable.
Fixes #65

Add success column to transactions

---

lib/malan/accounts.ex
lib/malan/accounts/user.ex
lib/malan/utils.ex
lib/malan_web/controllers/session_controller.ex
lib/malan_web/views/error_view.ex
test/malan/accounts_test.exs
test/malan_web/controllers/session_controller_test.exs
test/malan_web/controllers/user_controller_test.exs
test/support/helpers/accounts.ex

If the user has a list of approved IPs set, the login attempt
should be rejected if the user's IP is not on the list.
Also clean up some warnings and apply some formatting fixes.
Fixes #85

Reject login attempts from unapproved IPs

---

lib/malan_web/controllers/fallback_controller.ex
lib/malan_web/controllers/pagination_controller.ex
lib/malan_web/views/error_view.ex
test/malan_web/controllers/session_controller_test.exs
test/malan_web/controllers/user_controller_test.exs
test/malan_web/views/error_view_test.exs

Without throwing away useful data for the user.  This also removes the
errors attribute and makes the children root level members.
Improves response when pagination is incorrect.
Updates all tests and fix a few bugs ran into
Fixes #99
Fixes FreedomBen/libmalan#24

Make 422 errors with changeset info more consistent

---

lib/malan/accounts.ex
lib/malan/accounts/session.ex
lib/malan/utils.ex
lib/malan_web/controllers/auth_controller.ex
lib/malan_web/controllers/user_controller.ex
lib/malan_web/views/error_view.ex
scripts/curl/session_token_expires.sh
test/malan/accounts_test.exs
test/malan_web/controllers/auth_controller_test.exs
test/malan_web/controllers/user_controller_test.exs
test/support/helpers/accounts.ex

Add curl script for testing token expiration
Cleanup some warnings and apply formatting fixes
Fix return code in User whoami endpoint
whoami endpoint returned 404 when a token was expired or revoked, which is not ideal.  We accepted it as a bug before but now we want to add user experience for logging in after a session expires, so this needed to be fixed.
Fixes #101
Fix small bug in auth error reporting and add more test coverage
Add token_expired to 403 when token is expired
If the token is expired (or revoked) there will be a property "token_expired" in the 403 return body.
Fixes #102

Include expired in 403

---

config/runtime.exs
lib/malan/accounts.ex
lib/malan/utils.ex
test/malan/utils_test.exs

Add env var to disable TLS in release mode
When running malan locally, sometimes we use the production/release
build.  In that situation we often don't have TLS set up locally, so
wish to disable it. 
This adds an env var "DATABASE_TLS_ENABLED" which can be explicitly set 
to false in order to disable TLS.  If absent, the default is true
(require TLS)
Add Utils functions for explicitly true/false
When converting a string to a boolean, we need a default.  These
functions provide a default

Add escape hatch for tls in prod

---

lib/malan/accounts/user.ex
livebooks/query_birthdays.exs
priv/repo/migrations/20220510231539_change_birthday_to_date.exs
test/malan_web/controllers/user_controller_test.exs

The original idea was that "birth" can occur at specific times,
so a datetime was a good type. However in practice that extra
precision can complicate things when timezones come into play.
To avoid this problem, it would be best to have birthday be a
date instead of a datetime
Note:  For actually changing the data in postgres, this migration relies
on postgres automatic date conversion.  It was tested with a broad range
of datetimes, and each time the hours/minutes/seconds portion was
dropped and the date itself was kept by postgres.
Fixes #107

Change birthday type in schema to date rather than datetime

---

lib/malan_web/controllers/session_controller.ex
lib/malan_web/controllers/user_controller.ex
lib/malan_web/views/address_view.ex
lib/malan_web/views/phone_number_view.ex
lib/malan_web/views/session_view.ex
lib/malan_web/views/transaction_view.ex
lib/malan_web/views/user_view.ex
test/malan_web/controllers/session_controller_test.exs
test/malan_web/controllers/user_controller_test.exs

- Add `ok: true` to success responses for users and sessions.  
- Also add the `code: 200` to success responses.
- Also improve the tests a bit to check for more things
- Refactor template code to be more thorough and cleaner
Fixes #110

Return ok true users sessions

---

lib/malan/accounts.ex
test/malan_web/controllers/user_controller_test.exs

When deleting a user, revoke all active sessions
When a user is deleted, all of their active sessions should be
automatically revoked.  The session isn't usable for anything, but
should be revoked nonetheless for completeness.
Adds a handful of tests around this functionality.  Updates some tests
that were impacted.  Adds a test for access control around user deletion
to ensure that only admins or the user themselves can delete the user.
Fixes #112
Add test for whoami endpoint /api/users/whoami on user deletion
Add test to make sure that after a user is deleted, the whoami call does
not succeed.  It should 403 with token expired or revoked.

When deleting a user, revoke all active sessions

---

lib/malan/utils.ex
test/malan/utils_test.exs

This is a useful utility function, but as written requires ecto as
a dependency.  This is fine for phoenix apps, but horrible for
non-phoenix apps.
Refactor the function to work the same but without the dependency on
Ecto
Also adds some uniqueness tests to supplement the existing format tests

Refactor uuidgen to remove dependency on Ecto

---

lib/malan_web/controllers/user_controller.ex

In the User Controller we don't want to use the exception throwing
version of these methods.
Fixes #118

Use the exception-free version of user get functions

---

mix.exs
test/malan/accounts_test.exs
test/malan_web/controllers/session_controller_test.exs
test/malan_web/controllers/user_controller_test.exs
test/support/test_utils.ex
test/tests/test_utils_test.exs

commit 8af05858a5bae8b5b7b6bc38c7b6a93975881b68
Author: Benjamin Porter <FreedomBen@users.noreply.github.com>
Date:   Thu Aug 11 19:51:29 2022 -0600
Automatically seed test database
The tests expect the seeds to be in place, so we should automatically
run them to ensure database consistency for the test environment
Fixes #122
commit 02d02ba12eecda7eb8aaf268d786a76e572e4c6b
Author: Benjamin Porter <FreedomBen@users.noreply.github.com>
Date:   Thu Aug 11 18:47:23 2022 -0600
Fix up flaky tests
Rewrite the pagination tests to be permissive on the order in which they
are returned.  This fixes a fragility in pagination tests.
- The flakiness is a result of the tests expecting a deterministic order for objects created
- Running tests serially (synchronously) makes no difference
- Running tests …

Fix flaky pagination tests

---

lib/malan/accounts.ex
priv/repo/seeds.exs
test/malan/accounts_test.exs

`#Accounts.get_user_by/1` and `#Accounts.get_user_by!/1` need to omit
results for "deleted" users.  This makes them do that and adds some
tests to verify.

Fix `#Accounts.get_user_by/1` for deleted users

---

lib/malan/utils.ex
test/malan/utils_test.exs

These should work on structs as well as Access types.  Add some additional tests to verify that they do.

Add some robustness to path-parsing utility functions

---

Dockerfile.arm
Dockerfile.arm.prod

almalinux isn't available for ARM, so we need to use an alternative. This switches to the official elixir docker image on ARM, but incorporates the latest changes to the almalinux docker files

Fix ARM Dockerfiles

---

lib/malan/utils.ex
test/malan/utils_test.exs

the json decoder was choking on an object that was being converted from struct to map, which removed the encoders ability to recognize them.
Also adds a test to provide test coverage on this for the future.

Fix Jason Decoder bug

---

lib/malan/exceptions.ex
lib/malan/pagination.ex
lib/malan_web/controllers/log_controller.ex
lib/malan_web/controllers/pagination_controller.ex
lib/malan_web/controllers/session_controller.ex
lib/malan_web/controllers/user_controller.ex
test/malan/pagination_test.exs
test/malan_web/controllers/pagination_controller_test.exs

This way there's not an awkward centralized spot for adjusting the tables that correspond to paginated models.

Pagination rework

---

k8s/prod/deploy.yaml

with 4 instances currently we are using 20 connections.  There are 47 / 97 connections still available during peak traffic.  This would increase us from 20 connections to 28, leaving 39 connections still unused.  I think it should be pretty safe and still leaves us with a lot of overhead in case of traffic bursts on other applications sharing the db

Increase pool size for prod instances from 5 to 7

---

lib/malan/accounts/session.ex

I observed this error from a session that likely predated the extension rollout:
> #SessionController.delete/2 - Session deletion failed: extendable_until: can’t be blank
I'm not aware of way that `extendable_until` relates to session deletion, so I am proposing that it not be required.

allow deleting sessions without extendable_until

---

config/prod.exs
config/runtime.exs
config/test.exs
docker-compose-example.yml
docker-compose.yml

This change allows an env var of LOG_LEVEL to be set to a valid log level to override the default for the environment.  Prior behavior will remain the same unless LOG_LEVEL is set to a non-empty value

Allow runtime setting of log level

---

priv/static/.well-known/assetlinks.json

This PR adds an entry to the array in `assetlinks.json` for Connect Mobile Staging, and also updates the fingerprint for Connect Mobile.
Hopefully this fixes our issue with the deep linking not working on Android: https://github.com/Ameelio/connect-mobile/pull/1211#issuecomment-2867535721

JR/add new/updated fingerprints for Connect Android apps
